### ISSUE TITLE
Add Header to the web page

### ISSUE THREAD

**Issue by ShouryaSrivastava01** [ShouryaSrivastava01/weather-application#1]

**Comment by sdeepanshu17** [comment]
Please assign this to me.

**Comment by ShouryaSrivastava01** [comment]
Assigned ✅

**Comment by MasterIfeanyi** [comment]
I would love to be assigned this issue.

**Comment by Anshuman047** [comment]
Hey @ShouryaSrivastava01 , looking forward to contribute in this issue, it would be my first contribute during hacktoberfest..

**Comment by ShouryaSrivastava01** [comment]
@Anshuman047 already assigned, you can work of #3

**Comment by sdeepanshu17** [comment]
@ShouryaSrivastava01  Can you please provide with a basic design and layout of the header so that I can work accordingly?

**Comment by ShouryaSrivastava01** [comment]
@sdeepanshu17 


use can follow the given design
https://www.figma.com/file/QSxDCxE2BAUMfjHHJMw1ca/Untitled

💡 Tips : Google Font is used for the Title of the website. Don't change the font style. 
https://fonts.google.com/specimen/Press+Start+2P?preview.text=Mausam&preview.text_type=custom

logo : ![clouds](https://user-images.githubusercontent.com/72685413/193112102-bc94a4b6-c755-4f35-93bd-b120b20ae967.png)

Follow the best practices & add images in assets directory only.
