### ISSUE TITLE
Add Github link in the header

### ISSUE THREAD

**Issue by ShouryaSrivastava01** [ShouryaSrivastava01/weather-application#10]
add clickable Github link of this repository in the header. use the design given below.
https://www.figma.com/file/QSxDCxE2BAUMfjHHJMw1ca/Untitled?node-id=0%3A1

find the Github logo in the assets directory of the repository.

**Comment by aanchal-fatwani** [comment]
Hi, @ShouryaSrivastava01 , I would like to work on this issue. Please assign it to me to allow me to proceed further. Thanks

**Comment by ShouryaSrivastava01** [comment]
@aanchal-fatwani assigned ✅✅

**Comment by KarthikS373** [comment]
Hi @ShouryaSrivastava01 I would like to contribute over this one. can you please assign it to me
