### ISSUE TITLE
Implement UI in search box component

### ISSUE THREAD

**Issue by ShouryaSrivastava01** [ShouryaSrivastava01/weather-application#2]
https://www.figma.com/file/nCUXdlJglx8iV3m9EqAT3M/Untitled?node-id=0%3A1

Style according to the given UI. 
Note : No need to change Javascript or add new icons. Only work on the CSS part.

**Comment by najeebkp** [comment]
Hi @ShouryaSrivastava01  Please assign me this task.

**Comment by ShouryaSrivastava01** [comment]
assigned ✅

**Comment by codewithnadeem14502** [comment]
can i work on it ???

**Comment by ShouryaSrivastava01** [comment]
> 

already assigned please look for another issue 👍👍👍
