### ISSUE TITLE
Add footer to the web application

### ISSUE THREAD

**Issue by ShouryaSrivastava01** [ShouryaSrivastava01/weather-application#3]
https://www.figma.com/file/QSxDCxE2BAUMfjHHJMw1ca/Untitled

Please follow the above design.

**Comment by Anshuman047** [comment]
hey @ShouryaSrivastava01 , could i contribute in this issue..?

**Comment by ShouryaSrivastava01** [comment]
@Anshuman047 yes you can ✔✔

**Comment by Anshuman047** [comment]
Thank you very much for this opportunity..

**Comment by tanitoluwam** [comment]
Hi, @ShouryaSrivastava01 , I would love to contribute to this issue.. can i go ahead?

**Comment by sdeepanshu17** [comment]
I have completed making the footer please assign me so that I can submit the PR.

**Comment by Noothan-am** [comment]
hey @ShouryaSrivastava01 I have sent a pull request about this issue as I am new to opensource I am not understanding how to see it

**Comment by Noothan-am** [comment]
@ShouryaSrivastava01 please merge the pr  i sent about this issue
