### ISSUE TITLE
Image not rendering

### ISSUE THREAD

**Issue by ShouryaSrivastava01** [ShouryaSrivastava01/weather-application#30]
<img width="498" alt="image" src="https://user-images.githubusercontent.com/72685413/193768775-53e11b68-ecd7-44fe-87b6-cd7e44ec6ece.png">

**Comment by czlucius** [comment]
Would like to work on this.

**Comment by ShouryaSrivastava01** [comment]
@czlucius Let me brief about the issue.
Actually image (assets/moon.png) is not rendering in github pages, but in  other deployed version of website, this image is rendering.

**Comment by czlucius** [comment]
Ok, I have added a PR fixing this issue.
The moon image uses an absolute URL, which causes it to point towards `https://shouryasrivastava01.github.io/assets/moon.png` instead of `https://shouryasrivastava01.github.io/weather-application/assets/moon.png`
