### ISSUE TITLE
Add Autocomplete search suggestion

### ISSUE THREAD

**Issue by ShouryaSrivastava01** [ShouryaSrivastava01/weather-application#4]
add functionality to autocomplete search suggestion for city.
When a user enters the name of a city, give them suggestions of cities

eg : 
![image](https://user-images.githubusercontent.com/72685413/193105680-56504884-d079-487b-8dda-27caa970ef26.png)

**Comment by ashishpetwal** [comment]
I would like to work on this issue! Kindly assign it to me...

**Comment by ShouryaSrivastava01** [comment]
@ashishpetwal assigned ✔✔

**Comment by KarthikS373** [comment]
Is this still pending. If so I would like to work on this

**Comment by ashishpetwal** [comment]
@KarthikS373 i am currently working on this! will let you know if any help is needed

**Comment by jivteshsingh** [comment]
If this issue is still there, I would like to work on it. Can u please assign me this issue.

**Comment by jivteshsingh** [comment]
@ShouryaSrivastava01

**Comment by ShouryaSrivastava01** [comment]
@KarthikS373 @jivteshsingh you guys can work on it

**Comment by ShouryaSrivastava01** [comment]
any progress guys. if someone is working on it then share your working idea for this.
You might get help.

**Comment by jivteshsingh** [comment]
Hey @ShouryaSrivastava01, I am currently working on it just need some time to make it better

**Comment by MajorReact** [comment]
I'd love to give it a try. Can you assign this issue to me?
