### ISSUE TITLE
IMPROVING UI OF FORCAST CARD

### ISSUE THREAD

**Issue by A-1198** [ShouryaSrivastava01/weather-application#44]
Sir i want to improve the UI related to the extended Weather forcast .

**Comment by ShouryaSrivastava01** [comment]
@A-1198 please share your idea first before implementing any chances

**Comment by A-1198** [comment]
@ShouryaSrivastava01 i want to adjust the icons with a bit of spacing and better padding

**Comment by ShouryaSrivastava01** [comment]
@A-1198 go ahead then.

**Comment by A-1198** [comment]
@ShouryaSrivastava01 thanks
